### ISSUE TITLE
Command 'Ask ChatGPT' resulted in an error (command 'chatgpt.ask' not found)

### ISSUE THREAD

**Issue by wmelton** [mpociot/chatgpt-vscode#4]
Installing on Mac. After running `vsce package` to create the `vsix` file, I install the plugin locally. The icon is added to the sidebar, but when I click the icon, there is no output or prompt. 

When running cmd+shift+p and then selecting `Ask ChatGPT`, I receive `Command 'Ask ChatGPT' resulted in an error (command 'chatgpt.ask' not found)`

Is there a different path to installing and using the plugin that should be used? 

; node bin location = nvm/versions/node/v16.14.2/bin/node
; node version = v16.14.2
; npm version = 8.19.2

**Comment by jadengentry10** [comment]
I had the same issue, this guys comment fixed it for me: https://github.com/mpociot/chatgpt-vscode/issues/1#issuecomment-1337384976
Hope it helps!
