### ISSUE TITLE
[Suggestion] "ChatGPT: Check comments"

### ISSUE THREAD

**Issue by sergei-kashlikov** [mpociot/chatgpt-vscode#54]
It would be great to have an ability to select the comment section and ask ChatGPT to check the grammar, or to make more sense in the comments. For example, I write comments in English language, but it isn't my native language and I make mistakes or I use incorrect words to describe the context. Or, may be, ask it to even write some template first.

**Comment by timkmecl** [comment]
Hi, if that's something you would be using often, you can change in the settings the prompt used for Write documentation command, for example,  so that you order it to rewrite the comments using better grammar/to add comments to the code/etc.
